// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCTD_-LUNL_Uyb90mFx8F_DriW6ncdSY8',
    appId: '1:872744557823:web:05913f3a13eebc96afc0ca',
    messagingSenderId: '872744557823',
    projectId: 'sriramkoddev',
    authDomain: 'sriramkoddev.firebaseapp.com',
    storageBucket: 'sriramkoddev.appspot.com',
    measurementId: 'G-P64S7JHHP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDutlVh2hhtCYNVFtEnYnv7fO1A21Ek4sY',
    appId: '1:872744557823:android:5704d32c4d2cb09cafc0ca',
    messagingSenderId: '872744557823',
    projectId: 'sriramkoddev',
    storageBucket: 'sriramkoddev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClRMjMitdJvAIpJuCChYmmtocD6BuU-k4',
    appId: '1:872744557823:ios:552485df9ea8bae6afc0ca',
    messagingSenderId: '872744557823',
    projectId: 'sriramkoddev',
    storageBucket: 'sriramkoddev.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClRMjMitdJvAIpJuCChYmmtocD6BuU-k4',
    appId: '1:872744557823:ios:a6c3112e6319f7e4afc0ca',
    messagingSenderId: '872744557823',
    projectId: 'sriramkoddev',
    storageBucket: 'sriramkoddev.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
